[workspace]

members = [
	"dcb",
	"dcb-io",
	"dcb-util",
	"dcb-exe",
	"dcb-bytes",
	"dcb-bytes-derive",
	"dcb-iso9660",
	"dcb-cdrom-xa",
	"dcb-tools/dcb-extractor",
	"dcb-tools/dcb-decompiler",
	"dcb-tools/drv-extractor",
	"dcb-tools/pak-extractor",
	"dcb-tools/model-set-extractor",
]
