[workspace]

members = [
	"dcb",
	"dcb-io",
	"dcb-util",
	"dcb-exe",
	"dcb-bytes",
	"dcb-bytes-derive",
	"dcb-iso9660",
	"dcb-cdrom-xa",
	"dcb-drv",
	"dcb-pak",
	"dcb-tools/dcb-extractor",
	"dcb-tools/dcb-decompiler",
	"dcb-tools/undrv",
	"dcb-tools/drv",
	"dcb-tools/unpak",
	"dcb-tools/model-set-extractor",
	"dcb-tools/dcb-iso2bin",
	"dcb-tools/dcb-bin2iso",
]
