[package]
name = "dcb-io"
version = "0.1.0"
authors = ["Filipe Rodrigues <filipejacintorodrigues1@gmail.com>"]
edition = "2018"

[dependencies]

# Dcb
dcb-bytes = { path = "../dcb-bytes" }
dcb-util = { path = "../dcb-util" }

# Log
log = "0.4"

# Util
byteorder = "1.3"
ascii = { version = "1.0", features = ["serde"] }
arrayref = "0.3"
int-conv = "0.1"
bitmatch = "0.1"
either = "1.6"
smallvec = "1.4"
num_enum = "0.5"

# Serde
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"

# Derives
derive_more = "0.99"
thiserror = "1.0"
ref-cast = "1.0"
dcb-bytes-derive = { path = "../dcb-bytes-derive" }

[dev-dependencies]

itertools = "0.9"
