[package]
name = "dcb-card-editor"
version = "0.1.0"
authors = ["Filipe Rodrigues <filipejacintorodrigues1@gmail.com>"]
edition = "2018"

[dependencies]
# Dcb
dcb = { path = "../../dcb" }
dcb-util = { path = "../../dcb-util" }
dcb-cdrom-xa = { path = "../../dcb-cdrom-xa" }

# Gui
eframe = "0.11.0"

# Error
anyhow = "1.0.40"

# Utils
native-dialog = "0.5.5"
