[package]
name = "dcb-iso9660"
version = "0.1.0"
authors = ["Filipe Rodrigues <filipejacintorodrigues1@gmail.com>"]
edition = "2018"

[dependencies]


# Dcb
dcb-util = { path = "../dcb-util" }
dcb-bytes = { path = "../dcb-bytes" }

# Log
log = "0.4"

# Util
byteorder = "1.3"
bitflags = "1.2.1"
crc = "1.8.1"

# Derives
thiserror = "1.0"
ref-cast = "1.0"
